### ISSUE TITLE
Fails to run on android

### ISSUE THREAD

**Issue by nehamallama** [ByneappLLC/flutter_config#30]
I have made sure to pub get, restart the app, delete the app from the device etc and I still am not having any luck getting the env vars to work on android. This is the error I get when I run with android. Please let me know what other relevant info is needed. Everything looks ok when I run flutter doctor

```
D/EGL_emulation(21864): eglMakeCurrent: 0xe78b3020: ver 3 0 (tinfo 0xcba2a610)
E/flutter (21864): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method loadEnvVariables on channel flutter_config)
E/flutter (21864): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (21864): <asynchronous suspension>
E/flutter (21864): #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:359:43)
E/flutter (21864): <asynchronous suspension>
E/flutter (21864): #2      FlutterConfig.loadEnvVariables (package:flutter_config/flutter_config.dart:21:9)
E/flutter (21864): <asynchronous suspension>
E/flutter (21864): #3      main (package:flutter_login_ui/main.dart:25:3)
E/flutter (21864): <asynchronous suspension>
E/flutter (21864): 
```

**Comment by sonhvse61570** [comment]
Hi @nehamallama ,
Have you fixed this bug already?.
Please share your solution.

Thanks,
