### ISSUE TITLE
Higher minimum deployment target

### ISSUE THREAD

**Issue by themindstorm** [ByneappLLC/flutter_config#6]
My Flutter app works fine for IOS, but when I add the flutter_config plugin I get the following error:

```
Launching lib/main.dart on iPhone 8 in debug mode...
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_config` from `.symlinks/plugins/flutter_config/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "flutter_config":
      In Podfile:
        flutter_config (from `.symlinks/plugins/flutter_config/ios`)
    Specs satisfying the `flutter_config (from `.symlinks/plugins/flutter_config/ios`)` dependency were found, but they required a higher minimum deployment target.
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'
Error running pod install
Error launching application on iPhone 8.
Exited (sigterm)
```

I tried `pod update` on the IOS folder in the app, but I get this error:

```
[!] CocoaPods could not find compatible versions for pod "flutter_config":
  In Podfile:
    flutter_config (from `.symlinks/plugins/flutter_config/ios`)

Specs satisfying the `flutter_config (from `.symlinks/plugins/flutter_config/ios`)` dependency were found, but they required a higher minimum deployment target.
```

Is there any fix?

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.3 18D42, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[!] Android Studio (not installed)
[✓] VS Code (version 1.42.0)
[✓] Connected device (1 available)
```

**Comment by ir2pid** [comment]
add this line on top of your Podfile located at `projectroot/ios/Podfile`

`platform :ios, "10.0"`

run 
pod repo update

**Comment by edTheGuy00** [comment]
@ir2pid yes that is correct.

Sorry I’ve been too busy at the moment.

**Comment by edTheGuy00** [comment]
Hi, I [commented out the `deployment_target`] This shouldn't cause any isues since this can be defined at the app level. Please let me know if you encounter any issues (https://github.com/ByneappLLC/flutter_config/blob/946c80318d082eb1965a775bf0a5601783c19a57/ios/flutter_config.podspec#L19)
